# Generated by Django 5.1.4 on 2024-12-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
